find_package(Boost COMPONENTS date_time REQUIRED)
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)
find_package(dune-common REQUIRED)
find_package(dune-geometry REQUIRED)
find_package(dune-grid REQUIRED)
find_package(opm-grid REQUIRED)
find_package(dune-istl REQUIRED)

if(TARGET opmupscaling)
  get_property(opm-upscaling_LIBS TARGET opmupscaling PROPERTY INTERFACE_LINK_LIBRARIES)
  if(opm-upscaling_LIBS MATCHES SuperLU::SuperLU)
    find_package(SuperLU REQUIRED)
  endif()
  if(opm-upscaling_LIBS MATCHES SuiteSparse::UMFPACK)
    find_package(SuiteSparse COMPONENTS UMFPACK REQUIRED)
  endif()
  if(opm-upscaling_LIBS MATCHES MPI::MPI)
    find_package(MPI REQUIRED)
  endif()
else()
  find_package(Boost COMPONENTS iostreams) # Only needed when we build opm-upscaling
  find_package(MPI)
  find_package(SuiteSparse COMPONENTS UMFPACK)
  find_package(SuperLU)
endif()
