find_package(Boost COMPONENTS date_time REQUIRED)
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)
find_package(dune-common REQUIRED)
find_package(dune-geometry REQUIRED)
find_package(dune-grid REQUIRED)
find_package(opm-grid REQUIRED)
find_package(dune-istl REQUIRED)
find_package(MPI)

if(TARGET opmupscaling)
  get_property(opm-upscaling_COMPILE_DEFINITIONS TARGET opmupscaling PROPERTY INTERFACE_COMPILE_DEFINITIONS)
  if(opm-upscaling_COMPILE_DEFINITIONS MATCHES HAVE_SUPERLU)
    find_package(SuperLU REQUIRED)
  endif()
  if(opm-upscaling_COMPILE_DEFINITIONS MATCHES HAVE_SUITESPARSE_UMFPACK)
    find_package(SuiteSparse COMPONENTS UMFPACK REQUIRED)
  endif()
else()
  find_package(Boost COMPONENTS iostreams) # Only needed when we build opm-upscaling
  find_package(SuiteSparse COMPONENTS UMFPACK)
  find_package(SuperLU)
endif()
